git-browse: select remote name

diff --git a/bin/git-browse b/bin/git-browse
--- a/bin/git-browse
+++ b/bin/git-browse
@@ -1,13 +1,33 @@
 #!/bin/bash
 
-set -e
+action=''
+remote_name=origin
+
+while [ $# != 0 ]; do
+    case $1 in
+        -r)
+        [[ $# < 2 ]] && echo "Error: No remote name" && exit 1
+        remote_name="$2"
+        shift
+        ;;
+
+        *)
+        if [[ -n "$action" ]]; then
+            echo "Only one action is required."
+            exit 1
+        fi
+        action="$1"
+        ;;
+    esac
+    shift
+done
 
 if ! git rev-parse 1>/dev/null 2>&1; then
     echo "ERROR: This isnt a git directory"
     exit 1
 fi
 
-git_url="$(git config --get remote.origin.url)"
+git_url="$(git config --get remote.${remote_name}.url)"
 git_url=${git_url%.git}
 
 git_protocol="$(echo "$git_url" | awk -v FS="(@|:)" '{print $1}')"
@@ -22,14 +42,13 @@ elif [[ "$git_protocol" == 'github' ]] || [[ "$git_protocol" == 'gitlab' ]]; the
     git_domain="${git_protocol}.com"
     git_url="https://${git_protocol}.com/${git_url#*:}"
 else
-    echo "ERROR: Remote origin is invalid"
+    echo "ERROR: Remote $remote_name is invalid"
     exit 1
 fi
 url="${git_url}"
 
-git_branch="$(git rev-parse --abbrev-ref HEAD 2> /dev/null)"
+git_branch="$(git rev-parse --abbrev-ref HEAD 2> /dev/null)" || git_branch=''
 
-action="$1"
 case "$action" in
     '') action='home' ;;
     '-') action='current' ;;
@@ -43,12 +62,19 @@ esac
 
 case "$action" in
     'home') url="$url" ;;
-    'current') url="$url/tree/${git_branch}" ;;
     'branches') url="$url/branches" ;;
     'issues') url="$url/issues" ;;
     'releases') url="$url/releases" ;;
     'tags') url="$url/tags" ;;
     'repo-settings') url="$url/settings/repository" ;;
+
+    'current')
+        if [[ -z "$git_branch" ]]; then
+            echo "Error: No branch"
+            exit 1
+        fi
+        url="$url/tree/${git_branch}"
+    ;;
 
     'wiki')
         if [[ "$git_domain" == 'gitlab.com' ]]; then
