bin/git-browse: Support Azure DevOps

diff --git a/bin/git-browse b/bin/git-browse
--- a/bin/git-browse
+++ b/bin/git-browse
@@ -1,54 +1,142 @@
 #!/bin/bash
 
-action=''
-remote_name=origin
+set -ue
 
-while [ $# != 0 ]; do
-    case $1 in
-        -r)
-            [[ $# -lt 2 ]] && echo "Error: No remote name" && exit 1
-            remote_name="$2"
-            shift
+main() {
+    parse_args "$@"
+
+    if ! git rev-parse 1>/dev/null 2>&1; then
+        fail "This isn't a git directory."
+    fi
+
+    extract_remote_url_and_domain
+
+    url="${remote_url}"
+
+    if [[ -z "${git_branch:-}" ]]; then
+        git_branch="$(git rev-parse --abbrev-ref HEAD 2> /dev/null)"
+        if [[ "$git_branch" == 'HEAD' ]]; then
+            git_branch=''
+        fi
+    fi
+    debug git_branch="$git_branch"
+
+    git_commit="$(git rev-parse HEAD 2> /dev/null)"
+    debug git_commit="$git_commit"
+
+    case "$action" in
+        help|h)        print_help ;;
+        home|'')       _open "$url" ;;
+        branches|b)    _open "$url/branches" ;;
+        issues|i)      _open "$url/issues" ;;
+        releases|r)    _open "$url/releases" ;;
+        tags|t)        _open "$url/tags" ;;
+
+        commits|c)
+            if [[ "$remote_api" = 'ado' ]]; then
+                _open "$url?version=$(get_ado_version)&_a=history"
+            else
+                _open "$url/commits/${git_branch}"
+            fi
+        ;;
+
+        current|tree|'-')
+            if [[ "$remote_api" = 'ado' ]]; then
+                _open "$url?version=$(get_ado_version)"
+            else
+                _open "$url/tree/${git_branch:-$git_commit}"
+            fi
+        ;;
+
+        create-pr|pr)
+            if [[ "$remote_api" = 'ado' ]]; then
+                require_git_branch
+                _open "$url/pullrequestcreate?sourceRef=${git_branch:-$git_commit}"
+            else
+                fail_unsupported
+            fi
+        ;;
+
+        wiki|w)
+            if [[ "$remote_api" == 'gitlab' ]]; then
+                _open "$url/wikis"
+            else
+                _open "$url/wiki"
+            fi
+        ;;
+
+        settings|s)
+            if [[ "$remote_api" == 'gitlab' ]]; then
+                _open "$url/edit"
+            else
+                _open "$url/settings"
+            fi
+        ;;
+
+        repo-settings|rs)
+            _open "$url/settings/repository"
         ;;
 
         *)
-            if [[ -n "$action" ]]; then
-                echo "Only one action is required."
-                exit 1
-            fi
-            action="$1"
+            print_help
+            fail "Unknown action $action"
         ;;
     esac
-    shift
-done
+}
 
-if ! git rev-parse 1>/dev/null 2>&1; then
-    echo "ERROR: This isnt a git directory"
+parse_args() {
+    action=''
+    remote_name='origin'
+    debug='false'
+
+    while [ $# != 0 ]; do
+        case $1 in
+            --branch|-b)
+                if [[ $# -lt 2 ]]; then
+                    fail "No git branch name."
+                fi
+                git_branch="$2"
+                shift
+            ;;
+            --remote|-r)
+                if [[ $# -lt 2 ]]; then
+                    fail "No remote name."
+                fi
+                remote_name="$2"
+                shift
+            ;;
+
+            --debug) debug='true' ;;
+
+            *)
+                if [[ -n "$action" ]]; then
+                    fail "Only one action is required."
+                fi
+                action="$1"
+            ;;
+        esac
+        shift
+    done
+
+    if [[ "$debug" == 'true' ]]; then
+        debug() {
+            echo "DEBUG: $@"
+        }
+
+        # set -x
+    else
+        debug() { return; }
+    fi
+}
+
+fail() {
+    echo >&2 "FAILED: $@"
     exit 1
-fi
+}
 
-git_url="$(git config --get "remote.${remote_name}.url")"
-git_url=${git_url%.git}
-
-git_protocol="$(echo "$git_url" | awk -v FS="(@|:)" '{print $1}')"
-if [[ "$git_protocol" == 'http' ]] || [[ "$git_protocol" == 'https' ]]; then
-    git_domain="$(echo "$git_url" | awk -F'/' '{print $3}')"
-    git_url="$git_url"
-elif [[ $git_protocol == 'git' ]]; then
-    git_url="${git_url#*@}"
-    git_domain="$(echo "$git_url" | awk -F':' '{print $1}')"
-    git_url="https://${git_url/:/\/}"
-elif [[ "$git_protocol" == 'github' ]] || [[ "$git_protocol" == 'gitlab' ]]; then
-    git_domain="${git_protocol}.com"
-    git_url="https://${git_protocol}.com/${git_url#*:}"
-else
-    echo "ERROR: Remote $remote_name is invalid"
-    exit 1
-fi
-
-url="${git_url}"
-
-git_branch="$(git rev-parse --abbrev-ref HEAD 2> /dev/null)" || git_branch=''
+info() {
+    echo "INFO: $@"
+}
 
 print_help () {
     echo -n '''
@@ -56,66 +144,78 @@ Usage: git (browse|go) ([|home] | [-|current] | [b|branches] | [c|commits] | [h|
 ''' | tail +2
 }
 
-case "$action" in
-    '') action='home' ;;
-    '-') action='current' ;;
-    b) action='branches' ;;
-    c) action='commits' ;;
-    h) action='help' ;;
-    i) action='issues' ;;
-    r) action='releases' ;;
-    s) action='settings' ;;
-    t) action='tags' ;;
-    w) action='wiki' ;;
-esac
 
-case "$action" in
-    'help') print_help; exit 0 ;;
-    'home') url="$url" ;;
-    'branches') url="$url/branches" ;;
-    'issues') url="$url/issues" ;;
-    'releases') url="$url/releases" ;;
-    'tags') url="$url/tags" ;;
-    'repo-settings') url="$url/settings/repository" ;;
+extract_remote_url_and_domain() {
+    original_remote_url="$(git config --get "remote.${remote_name}.url")"
+    debug original_remote_url="$original_remote_url"
 
-    'commits')
-        if [[ -z "$git_branch" ]]; then
-            echo "Error: No branch"
-            exit 1
-        fi
-        url="$url/commits/${git_branch}"
-    ;;
+    remote_url=${original_remote_url%.git}
 
-    'current')
-        if [[ -z "$git_branch" ]]; then
-            echo "Error: No branch"
-            exit 1
-        fi
-        url="$url/tree/${git_branch}"
-    ;;
+    git_protocol="$(echo "$remote_url" | awk -v FS="(@|:)" '{print $1}')"
+    debug git_protocol="$git_protocol"
 
-    'wiki')
-        if [[ "$git_domain" == 'gitlab.com' ]]; then
-            url="$url/wikis"
-        else
-            url="$url/wiki"
-        fi
-    ;;
+    if [[ "$git_protocol" == 'http' ]] || [[ "$git_protocol" == 'https' ]]; then
+        remote_domain="$(echo "$remote_url" | awk -F'/' '{print $3}')"
+        remote_url="$remote_url"
+    elif [[ $git_protocol == 'git' ]]; then
+        remote_url="${remote_url#*@}"
+        remote_domain="$(echo "$remote_url" | awk -F':' '{print $1}')"
+        remote_url="https://${remote_url/:/\/}"
+    elif [[ "$git_protocol" == 'github' ]] || [[ "$git_protocol" == 'gitlab' ]]; then
+        remote_domain="${git_protocol}.com"
+        remote_url="https://${git_protocol}.com/${remote_url#*:}"
+    else
+        fail "Remote $remote_name is invalid. Remote URL: $remote_url"
+    fi
 
-    'settings')
-        if [[ "$git_domain" == 'gitlab.com' ]]; then
-            url="$url/edit"
-        else
-            url="$url/settings"
-        fi
-    ;;
+    debug remote_url="$remote_url"
+    debug remote_domain="$remote_domain"
 
-    *)
-        echo "ERROR: Unknown action $action"
-        print_help
-        exit 1
-    ;;
-esac
+    if [[ "$remote_domain" = 'github.com' ]]; then
+        remote_api='github'
+    elif [[ "$remote_domain" = 'gitlab.com' ]]; then
+        remote_api='gitlab'
+    elif [[ "$remote_domain" =~ ".visualstudio.com" ]]; then
+        remote_api='ado'
+    else
+        fail "Cannot infer API name from remote URL: $remote_url."
+    fi
 
-echo "Opening URL: $url"
-open-url "$url"
+    debug remote_api="$remote_api"
+}
+
+require_git_branch() {
+    if [[ -z "$git_branch" ]]; then
+        fail "A git branch must be checked out."
+    fi
+}
+
+fail_unsupported() {
+    fail "Action is not supported for ${remote_api:-undefined} API."
+}
+
+get_ado_version() {
+    if [[ -n "$git_branch" ]]; then
+        echo "GB$git_branch"
+    else
+        echo "GC$git_commit"
+    fi
+}
+
+
+get_default_branch() {
+    default_branch="$(git config --get user.default-branch)"
+    if [[ -z "$default_branch" ]]; then
+        default_branch='master'
+    fi
+    echo "$default_branch"
+}
+
+_open() {
+    local url="$1"
+
+    info "Opening URL: $url"
+    open-url "$url"
+}
+
+main "$@"
