rename shortcuts to marks

diff --git a/bin/marks b/bin/marks
--- a/bin/marks
+++ b/bin/marks
@@ -6,9 +6,9 @@ source ~/.dotfiles.env
 source "$DOTFILES_HOME/bin/lib/can_execute"
 source "$DOTFILES_HOME/bin/lib/polyfills.sh"
 
-config_file="$(custom-env-resolve 'config/shortcuts.tsv')"
+config_file="$(custom-env-resolve 'config/marks.tsv')"
 
-list_shortcuts () {
+list_marks () {
     local long='true'
     [[ "$1" == '-s' ]] && { long='false'; }
 
@@ -22,14 +22,14 @@ list_shortcuts () {
     fi
 }
 
-add_shortcut () {
+add_mark () {
     local interactive='true'
     [[ "$1" == '-f' ]] && { interactive='false'; shift; }
     if [[ "$#" -lt 1 ]]; then
-        echo >&2 "Usage: $0 add SHORTCUT [PATH]"
+        echo >&2 "Usage: $0 add MARK [PATH]"
         return 1
     fi
-    local shortcut="$1"
+    local mark="$1"
 
     local path
     if [[ "$#" -lt 2 ]]; then
@@ -38,15 +38,15 @@ add_shortcut () {
         path="$(realpath -s "$2")"
     fi
 
-    local line="$(cat "$config_file" | grep "^${shortcut}\s\+")"
+    local line="$(cat "$config_file" | grep "^${mark}\s\+")"
     if [[ -n "$line" ]]; then
-        echo >&2 "Shortcut ${shortcut} exists. Remove it first"
-        remove_shortcut "${shortcut}" || return 1
+        echo >&2 "Mark ${mark} exists. Remove it first"
+        remove_mark "${mark}" || return 1
     fi
 
     local response
     if [ "$interactive" = 'true' ]; then
-        printf "Add %s => %s ? ([y]/n) " "$shortcut" "$path"
+        printf "Add %s => %s ? ([y]/n) " "$mark" "$path"
         read -r response
     else
         response='y'
@@ -56,22 +56,22 @@ add_shortcut () {
         return 1
     fi
 
-    echo "${shortcut}"$'\t'"${path}" | tee -a "$config_file" | sed 's/^/>> /'
-    update_shortcuts
+    echo "${mark}"$'\t'"${path}" | tee -a "$config_file" | sed 's/^/>> /'
+    update_marks
     return 0
 }
 
-remove_shortcut () {
+remove_mark () {
     local interactive='true'
     [[ "$1" == '-f' ]] && { interactive='false'; shift; }
     if [[ "$#" -lt 1 ]]; then
-        echo >&2 "Usage: $0 remove SHORTCUT"
+        echo >&2 "Usage: $0 remove MARK"
         return 1
     fi
-    local shortcut="$1"
-    local line="$(cat "$config_file" | grep "^${shortcut}\s\+")"
+    local mark="$1"
+    local line="$(cat "$config_file" | grep "^${mark}\s\+")"
     if [[ -z "$line" ]]; then
-        echo >&2 "Cannot find shortcut ${shortcut}"
+        echo >&2 "Cannot find mark ${mark}"
         return 1
     fi
 
@@ -79,7 +79,7 @@ remove_shortcut () {
 
     local response
     if [ "$interactive" = 'true' ]; then
-        printf "Remove %s => %s ? ([y]/n) " "$shortcut" "$path"
+        printf "Remove %s => %s ? ([y]/n) " "$mark" "$path"
         read -r response
     else
         response='y'
@@ -89,26 +89,26 @@ remove_shortcut () {
         return 1
     fi
 
-    sed "/^${shortcut}\s\+/d" -i "$config_file"
-    update_shortcuts
+    sed "/^${mark}\s\+/d" -i "$config_file"
+    update_marks
     return 0
 }
 
-update_shortcuts () {
-    "$DOTFILES_HOME/bin/update-shortcuts" > /dev/null
+update_marks () {
+    "$DOTFILES_HOME/bin/update-marks" > /dev/null
 }
 
 if [[ "$#" = '0' ]]; then
-    list_shortcuts "$@"
+    list_marks "$@"
     exit
 fi
 
 subcommand="$1"
 shift
 case "$subcommand" in
-    add) add_shortcut "$@" ;;
-    list) list_shortcuts "$@" ;;
-    remove) remove_shortcut "$@" ;;
-    update) update_shortcuts "$@" ;;
+    add) add_mark "$@" ;;
+    list) list_marks "$@" ;;
+    remove) remove_mark "$@" ;;
+    update) update_marks "$@" ;;
     *) echo >&2 "Usage: $0 [add|list|remove|update]"; exit 1 ;;
 esac
