bin/pcp: follow links and log errors

diff --git a/bin/pmv b/bin/pmv
--- a/bin/pmv
+++ b/bin/pmv
@@ -13,7 +13,30 @@ target_dir="$2"
 mkdir -pv "$target_dir"
 target_dir="$(realpath "$target_dir")"
 
-cd "$source_dir"
-find -type f -print0 |
-    # sort |
-    xargs -0 -P128 -n8 bash -c 'target_dir="$1"; shift; for f in "$@"; do echo "$f"; mkdir -pv "$target_dir/$(dirname "$f")"; yes y | cp -v "$f" "$target_dir/$f"; done' 'arg_0' "$target_dir"
+errors_log="$(mktemp /tmp/pmv-errors-XXXXXX)"
+
+command='''
+target_dir="$1"; shift
+
+for source_path in "$@"; do
+    echo "$source_path"
+    mkdir -pv "$target_dir/$(dirname "$source_path")"
+    target_path="$target_dir/$source_path"
+    [[ -d "$target_path" ]] && {
+        echo "Cannot copy file to directory path: $target_path" >&2
+        exit 1
+    }
+    command mv-v "$source_path" "$target_path"
+done
+'''
+
+print_errors() {
+    echo "Errors log at: $errors_log"
+    "${PAGER:-less}" "$errors_log"
+}
+
+(
+    cd "$source_dir"
+    find -L -not -type d -print0 |
+        xargs -0 -P128 -n8 bash -c "$command" 'arg_0' "$target_dir" 2> >(tee -a "$errors_log") || print_errors
+)
