move locking from youtube-dl job to youtube-dl-watch-later

diff --git a/bin/youtube-dl-watch-later b/bin/youtube-dl-watch-later
--- a/bin/youtube-dl-watch-later
+++ b/bin/youtube-dl-watch-later
@@ -14,6 +14,7 @@ PLAYLIST='WL'
 URL="https://youtube.com/playlist?list=$PLAYLIST"
 COOKIE_FILE="$YOUTUBE_HOME/.downloader/cookies.txt"
 COMMON_ARGS='-f 18 --sub-lang en,ar --write-auto-sub --continue --mark-watched --ignore-errors'
+LOCK_FILE="$YOUTUBE_HOME/.downloader/lock"
 
 cd "$YOUTUBE_HOME"
 if [ ! -d .downloader ]; then
@@ -27,4 +28,20 @@ else
     exit 1
 fi
 
+sigint_trap () {
+    echo 'SIGINT received'
+    rm -vf LOCK_FILE
+}
+trap 'sigint_trap' SIGINT
+
+# acquire lock
+if [ -f "$LOCK_FILE" ]; then
+    echo "Cannot acquire lock at $LOCK_FILE"
+    exit 1
+else
+    touch $LOCK_FILE
+fi
+
 $YOUTUBE_DOWNLADER $COMMON_ARGS --cookie "$COOKIE_FILE" "$URL"
+
+[ -f $LOCK_FILE ] && rm -vf "$LOCK_FILE"  # release lock
