log sub processes output

diff --git a/config/crontab/crontab-jobs/updatedrive b/config/crontab/crontab-jobs/updatedrive
--- a/config/crontab/crontab-jobs/updatedrive
+++ b/config/crontab/crontab-jobs/updatedrive
@@ -4,14 +4,15 @@ source ~/.dotfiles_config
 source "$DOTFILES_HOME/bin/utils/log"
 export PATH="$DOTFILES_HOME/bin:$PATH"
 
+DRIVE_PATH="$DOTFILES_CONFIG_GOOGLE_DRIVE_ROOT"
+LOG_FILE="$DRIVE_PATH/.updatedrive.log.driveignored"
+exec > >(tee -a "$LOG_FILE") 2>&1
+
 if ! ok-to-download; then
     info "Aborted! Current connection is not allowed to download"
     exit 1
 fi
 
-DRIVE_PATH="$DOTFILES_CONFIG_GOOGLE_DRIVE_ROOT"
-LOG_FILE="$DRIVE_PATH/../.drive-log"
-
 info "Starting sync..."
-updatedrive --no-prompt >> "$LOG_FILE" 2>&1 || error "failed"
+updatedrive --no-prompt || error "failed"
 info "Finished"
