export paths from dotfiles config file

diff --git a/config/crontab/crontab-jobs/youtube-dl b/config/crontab/crontab-jobs/youtube-dl
--- a/config/crontab/crontab-jobs/youtube-dl
+++ b/config/crontab/crontab-jobs/youtube-dl
@@ -1,7 +1,12 @@
 #!/bin/bash
 
 source ~/.dotfiles_config
-YOUTUBE_HOME='/mnt/Storage/Shared/youtube'
+if [ -z "$DOTFILES_CONFIG_YOUTUBE_HOME" ]; then
+    echo 'Cannot find youtube home directory'
+    exit 1
+fi
+
+YOUTUBE_HOME="$DOTFILES_CONFIG_YOUTUBE_HOME"
 YOUTUBE_WATCH_LATER_DOWNLOADER="$DOTFILES_ROOT/bin/youtube-dl-watch-later"
 YOUTUBE_LIST_DOWNLADER="$DOTFILES_ROOT/bin/youtube-dl-list"
 LOG_FILE="$YOUTUBE_HOME/download-log"
