youtube-dl: prevent multiple instances

diff --git a/config/crontab/crontab-jobs/youtube-dl b/config/crontab/crontab-jobs/youtube-dl
--- a/config/crontab/crontab-jobs/youtube-dl
+++ b/config/crontab/crontab-jobs/youtube-dl
@@ -9,10 +9,32 @@ fi
 YOUTUBE_HOME="$DOTFILES_CONFIG_YOUTUBE_HOME"
 YOUTUBE_WATCH_LATER_DOWNLOADER="$DOTFILES_HOME/bin/youtube-dl-watch-later"
 YOUTUBE_LIST_DOWNLADER="$DOTFILES_HOME/bin/youtube-dl-list"
-LOG_FILE="$YOUTUBE_HOME/.downloader/download-log"
+LOG_FILE="$YOUTUBE_HOME/.downloader/log"
+LOCK_FILE="$YOUTUBE_HOME/.downloader/lock"
 
-echo -e "\n====================\n" >> "$LOG_FILE" 2>&1
-date >> "$LOG_FILE" 2>&1
-echo -e "====================\n\n" >> "$LOG_FILE" 2>&1
-$YOUTUBE_WATCH_LATER_DOWNLOADER >> "$LOG_FILE" 2>&1
-$YOUTUBE_LIST_DOWNLADER >> "$LOG_FILE" 2>&1
+exec >> "$LOG_FILE" 2>&1  # redirect output and error to log file
+
+[ ! -d "$YOUTUBE_HOME/.downloader" ] && mkdir -pv "$YOUTUBE_HOME/.downloader"
+
+echo -e "\n====================\n"
+date
+echo -e "====================\n\n"
+
+sigint_trap () {
+    echo 'SIGINT received'
+    rm -vf LOCK_FILE
+}
+trap 'sigint_trap' SIGINT
+
+# acquire lock
+if [ -f "$LOCK_FILE" ]; then
+    echo "Cannot acquire lock at $LOCK_FILE"
+    exit 1
+else
+    touch $LOCK_FILE
+fi
+
+$YOUTUBE_WATCH_LATER_DOWNLOADER
+$YOUTUBE_LIST_DOWNLADER
+
+[ -f $LOCK_FILE ] && rm -vf "$LOCK_FILE"  # release lock
